import type { Product } from "@/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "High-quality wireless headphones with noise cancellation",
    category: "Electronics",
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Track your fitness goals with this advanced smartwatch",
    category: "Electronics",
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Comfortable and sustainable organic cotton t-shirt",
    category: "Clothing",
  },
  {
    id: "4",
    name: "Stainless Steel Water Bottle",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Insulated water bottle that keeps drinks cold for 24 hours",
    category: "Lifestyle",
  },
  {
    id: "5",
    name: "Wireless Phone Charger",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Fast wireless charging pad compatible with all devices",
    category: "Electronics",
  },
  {
    id: "6",
    name: "Yoga Mat Premium",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Non-slip premium yoga mat for all your workout needs",
    category: "Fitness",
  },
  {
    id: "7",
    name: "Coffee Mug Set",
    price: 34.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Set of 4 ceramic coffee mugs with elegant design",
    category: "Kitchen",
  },
  {
    id: "8",
    name: "Bluetooth Speaker",
    price: 89.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Portable speaker with 360-degree sound and 12-hour battery",
    category: "Electronics",
  },
  {
    id: "9",
    name: "Reading Glasses",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Stylish reading glasses with blue light protection",
    category: "Accessories",
  },
  {
    id: "10",
    name: "Desk Organizer",
    price: 27.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Bamboo desk organizer with multiple compartments",
    category: "Office",
  },
  {
    id: "11",
    name: "Wireless Mouse",
    price: 45.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Ergonomic wireless mouse with precision tracking",
    category: "Electronics",
  },
  {
    id: "12",
    name: "Plant Pot Set",
    price: 22.99,
    image: "/placeholder.svg?height=300&width=300",
    description: "Set of 3 ceramic plant pots with drainage holes",
    category: "Home & Garden",
  },
]
